c_compiler:         # [osx]
  - clang_bootstrap # [osx]
cxx_compiler:       # [osx]
  - clang_bootstrap # [osx]

cxx_compiler_version: # [linux and ppc64le]
  # linking error with gcc 9+ (relocation truncated to fit: R_PPC64_REL24 against symbol ...)
  - 8                 # [linux and ppc64le]
