c_compiler:
  - gcc                        # [linux]
  - clang_bootstrap            # [osx]
  - vs2022                     # [win]
cxx_compiler:
  - gxx                        # [linux]
  - clang_bootstrap            # [osx]
  - vs2022                     # [win]

c_compiler_version:
  - 11.2.0            # [linux]
  - 19.1.7            # [osx]
cxx_compiler_version:
  - 11.2.0            # [linux]
  - 19.1.7            # [osx]

c_stdlib_version:   # [win]
  - 2022.14         # [win]

cl_version:         # [win]
  - 19.44.35207     # [win]

runtime_version:    # [win]
  - 14.44.35208     # [win] 
