c_compiler:         # [osx]
  - clang_bootstrap # [osx]
cxx_compiler:       # [osx]
  - clang_bootstrap # [osx]

cxx_compiler_version: # [linux]
  - 10                # [linux and aarch64]
  - 9                 # [linux and not ppc64le and not aarch64]
  # linking error with gcc 9
  - 8                 # [linux and ppc64le]
