c_compiler:
  - clang_bootstrap            # [osx]
  - vs2022                     # [win]
cxx_compiler:
  - clang_bootstrap            # [osx]
  - vs2022                     # [win]

c_compiler_version:
  - 19.1.7            # [osx]
cxx_compiler_version:
  - 19.1.7            # [osx]

c_stdlib_version:   # [win]
  - 2022.14         # [win]
