# c_compiler:
#   - gcc                        # [linux]
#   - clang_bootstrap            # [osx]
#   - vs2022                     # [win]
# cxx_compiler:
#   - gxx                        # [linux]
#   - clang_bootstrap            # [osx]
#   - vs2022                     # [win]

c_compiler_version:
  - 11.2.0            # [linux]
  - 17.0.6            # [osx]
cxx_compiler_version:
  - 11.2.0            # [linux]
  - 17.0.6            # [osx]


CONDA_BUILD_SYSROOT:
  - /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk

# Bump up the version of build tools and runtime
cl_version:
  - 19.42.34440
tools_version:
  #TODO CHANGE BACK TO LESS RECENT VERSION
  - 17.13
# MSVC v143 - VS 2022 C++ x64/x86 build tools
msvc_version:
  - 143
