{% set version = "8.0.0" %}
{% set sha256 = "8872be1b12c61450cacc82b3d153eab02be2546ef34fa3580ed14137bb26224c" %}

{% set build_number = 2 %}
{% set major_ver = version.split(".")[0] %}

package:
  name: llvm
  version: {{ version }}

source:
  url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    - llvm-lto-static.patch   # [win]
    # TODO add back for sake of llvm-lit - partial-testing.patch
    - D47188-svml-VF.patch    # Fixes vectorizer and extends SVML support
    # Revert an upstream change for Numba
    # ref: https://github.com/numba/llvmlite/blob/v0.29.0/conda-recipes/0001-Revert-Limit-size-of-non-GlobalValue-name.patch
    - 0001-Revert-Limit-size-of-non-GlobalValue-name.patch


build:
  number: {{ build_number }}
  skip:  true  # [(win and vc<14) or aarch64 or ppc64le]

requirements:
  build:
    - {{ compiler('cxx') }}   # [not osx]
    - cmake
    - ninja     # [win]
    - python    3.7
    - make

test:
  files:
    - numba-3016.ll

  commands:
    - $PREFIX/bin/llvm-config --libs                         # [not win]
    - $PREFIX/bin/llc -version                               # [not win]

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1        # [win]

    - test -f $PREFIX/include/llvm/Pass.h                    # [unix]
    - test -f $PREFIX/lib/libLLVMCore.a                      # [not win]

outputs:
  # Contains everything
  - name: llvmdev
    script: install_llvm.sh                         # [not win]
    script: install_llvm.bat                        # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}    # [not osx]
        - cmake
        - ninja     # [win]
        - python    3.7
      run:
        - libllvm{{ major_ver }} {{ version }}
        - libcxx >={{ cxx_compiler_version }}  # [osx]
      run_constrained:
        - llvm-meta {{ version }}

  # Contains the shared libraries. To make different LLVM libraries co-installable
  # soversion is appended to the package name
  - name: libllvm{{ major_ver }}
    script: install_llvm.sh                         # [not win]
    script: install_llvm.bat                        # [win]
    files:
      - lib/libLLVM-{{ major_ver }}.so              # [linux]
      - lib/libLLVM-{{ major_ver }}.dylib           # [osx]
      - Library/bin/LLVM-{{ major_ver }}.dll        # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}    # [not osx]
        - cmake
        - ninja     # [win]
        - python    3.7
      run:
        - libcxx >={{ cxx_compiler_version }}  # [osx]

  # Contains LLVM tools and shared libraries
  - name: llvm
    build:
      run_exports:
        - libllvm{{ major_ver }}
    files:
      - dummy
    requirements:
      run:
        - libllvm{{ major_ver }}
      run_constrained:
        - llvm-meta {{ version }}
        - llvmdev   {{ version }}

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM

extra:
  recipe-maintainers:
    - inducer
    - pitrou
    - jakirkham
    - mingwandroid
    - mattwala
    - SylvainCorlay
    - isuruf
