{% set version = "20.1.8" %}
{% set major_ver = version.split(".")[0] %}
{% set tail_ver = version.split(".")[-1] %}
{% set maj_min = major_ver ~ "." ~ version.split(".")[1] %}

# as of LLVM 19, we expect an "-rcX" suffix for the release candidates
{% set extra = "-" ~ tail_ver if tail_ver not in "0123456789" else "" %}
{% set extra = "git" if tail_ver|trim("0123456789") == "dev" else extra %}

package:
  name: llvm-package
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-{{ version.replace(".rc", "-rc") }}.tar.gz
  sha256: a6cbad9b2243b17e87795817cfff2107d113543a12486586f8a055a2bb044963
  patches:
    - patches/0004-remove-unsupported-intrinsic-test.patch
    - patches/0005-remove-permission-based-unit-tests.patch

build:
  number: 0
  merge_build_host: false

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - python
    - libcxx-devel {{ version }}    # [osx]
    - patch                     # [not win]
    - m2-patch                  # [win]
    - m2-sed                    # [win]
    - git                       # [not win]
  host:
    - backtrace {{ backtrace }}         # [unix]
    - libxml2 {{ libxml2 }}
    - zlib {{ zlib }}
    - zstd {{ zstd }}
    - libcxx-devel {{ version }}  # [osx]

outputs:
  # Contains everything
  - name: llvmdev
    script: install_llvm.sh   # [unix]
    script: install_llvm.bat  # [win]
    build:
      activate_in_script: true
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - ninja
        - python
        - m2-sed                  # [win]
        - libcxx-devel {{ version }}  # [osx]
      host:
        - libcxx-devel {{ version }}  # [osx]
        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}
        - {{ pin_subpackage("libllvm-c" ~ major_ver, exact=True) }}     # [win]
        - {{ pin_subpackage("llvm-tools", exact=True) }}
        - zlib {{ zlib }}
        - zstd {{ zstd }}
      run:
        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}
        - {{ pin_subpackage("libllvm-c" ~ major_ver, exact=True) }}     # [win]
        - {{ pin_subpackage("llvm-tools", exact=True) }}
        # we need to do this manually because clang_bootstrap has no run-export
        - libcxx >={{ cxx_compiler_version }}                           # [osx]
      # run_constrained:
      #   - llvm        {{ version }}
      #   - llvm-tools  {{ version }}
      #   - clang       {{ version }}
      #   - clang-tools {{ version }}
    test:
      requires:
        - ripgrep  # [win]
      commands:
        - $PREFIX/bin/llvm-config --libs                                # [not win]
        - test -f $PREFIX/include/llvm/Pass.h                           # [not win]
        - test -f $PREFIX/lib/libLLVMCore.a                             # [not win]
        - $PREFIX/libexec/llvm/not false                                # [not win]
        - $PREFIX/bin/llvm-nm --help                                    # [not win]
        - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1               # [win]
        - if not exist "%LIBRARY_PREFIX%"\\libexec\llvm\not.exe exit 1  # [win]
        - if not exist "%LIBRARY_BIN%"\\llvm-nm.exe exit 1              # [win]
        - llvm-nm.exe --help                                            # [win]

        # ensure we've correctly inserted %VSINSTALLDIR% into the CMake metadata for LLVM;
        # we're looking for: `INTERFACE_LINK_LIBRARIES "$ENV{VSINSTALLDIR}/DIA SDK/lib/amd64/diaguids.lib;[...]`instead
        - rg -e "INTERFACE_LINK_LIBRARIES\s\"\$ENV\{VSINSTALLDIR\}[/\w\s]+/diaguids\.lib" %LIBRARY_LIB%\cmake\llvm\LLVMExports.cmake  # [win]

  # Contains the shared libraries. To make different LLVM libraries co-installable
  # soversion is appended to the package name.
  - name: libllvm{{ major_ver }}
    script: install_llvm.sh  # [not win]
    build:
      activate_in_script: true
      run_exports:                                                    # [not win]
        - {{ pin_subpackage("libllvm" ~ major_ver, max_pin="x.x") }}  # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - ninja                    # [not win]
        - cmake                    # [not win]
        - python                   # [not win]
        - libcxx-devel {{ version }}  # [osx]
      host:
        - libcxx-devel {{ version }}  # [osx]
        - libxml2 {{ libxml2 }} # [unix]
        - zlib {{ zlib }}
        - zstd {{ zstd }}
      run:
        # we need to do this manually because clang_bootstrap has no run-export
        - libcxx >={{ cxx_compiler_version }}  # [osx]
    test:
      commands:
        # old style
        - test -f $PREFIX/lib/libLLVM-{{ major_ver }}{{ extra }}.so     # [linux]
        - test -f $PREFIX/lib/libLLVM-{{ major_ver }}{{ extra }}.dylib  # [osx]
        # new style
        - test -f $PREFIX/lib/libLLVM.so.{{ maj_min }}{{ extra }}       # [linux]
        - test -f $PREFIX/lib/libLLVM.{{ maj_min }}{{ extra }}.dylib    # [osx]

  # This is a meta package so that people can use the latest libllvm and also
  # for run_exports
  - name: llvm
    build:
      run_exports:                                                    # [not win]
        - {{ pin_subpackage("libllvm" ~ major_ver, max_pin="x.x") }}  # [not win]
    requirements:
      build:
      host:
        - libxml2 {{ libxml2 }}
        - libffi {{ libffi }}
        - zlib {{ zlib }}
        - zstd {{ zstd }}
        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}     # [not win]
      run:                                                            # [not win]
        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}     # [not win]
      # run_constrained:
      #   - llvmdev     {{ version }}
      #   - llvm-tools  {{ version }}
      #   - clang       {{ version }}
      #   - clang-tools {{ version }}
    test:
      commands:
        - echo "Hello World!"

  # Contains LLVM tools with a version suffix
  - name: llvm-tools-{{ major_ver }}
    script: install_llvm.sh   # [unix]
    script: install_llvm.bat  # [win]
    build:
      activate_in_script: true
      # On Windows there are no symlinks and copying will create a new package
      # that is 300MB+
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - ninja
        - python >=3
        - libcxx-devel {{ version }}  # [osx]
      host:
        - libcxx-devel {{ version }}  # [osx]
        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}
        - zlib
        - zstd
      run:
        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}
        # we need to do this manually because clang_bootstrap has no run-export
        - libcxx >={{ cxx_compiler_version }}  # [osx]
    test:
      commands:
        - $PREFIX/bin/llc-{{ major_ver }} -version                               # [not win]
        # The test for windows is split into two lines instead of having it in one line
        # like its unix variant because of a YAML parsing issue.
        - if not exist "%LIBRARY_BIN%"\\llc-{{ major_ver }}.exe exit 1           # [win]
        - llc-{{ major_ver }} -version                                           # [win]
        - test ! -f $PREFIX/bin/llvm-config-{{ major_ver }}                      # [not win]
        - if exist "%LIBRARY_BIN%"\\llvm-config-{{ major_ver }}.exe exit 1       # [win]

  # Contains LLVM tools
  - name: llvm-tools
    script: install_llvm.sh   # [unix]
    script: install_llvm.bat  # [win]
    build:
      activate_in_script: true
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - ninja
        - python
        - libcxx-devel {{ version }}  # [osx]
      host:
        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}
        - {{ pin_subpackage("llvm-tools-" ~ major_ver, exact=True) }}   # [not win]
        # on unix, there's only symlinks
        - libxml2 {{ libxml2 }} # [win]
        - zlib {{ zlib }}      # [win]
        - zstd {{ zstd }}      # [win]
      run:
        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}
        - {{ pin_subpackage("llvm-tools-" ~ major_ver, exact=True) }}   # [not win]
      # run_constrained:
      #   - llvm        {{ version }}
      #   - llvmdev     {{ version }}
      #   - clang       {{ version }}
      #   - clang-tools {{ version }}
    test:
      commands:
        - $PREFIX/bin/llc -version                               # [not win]
        # The test for windows is split into two lines instead of having it in one line
        # like its unix variant because of a YAML parsing issue.
        - if not exist "%LIBRARY_BIN%"\\llc.exe exit 1           # [win]
        - llc -version                                           # [win]
        - test ! -f $PREFIX/bin/llvm-config                      # [not win]
        - if exist "%LIBRARY_BIN%"\\llvm-config.exe exit 1       # [win]

  # Contains LLVM-C shared library
  - name: libllvm-c{{ major_ver }}
    script: install_llvm.sh   # [unix]
    script: install_llvm.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("libllvm-c" ~ major_ver, max_pin="x.x") }}
      activate_in_script: true
      # not supported on linux, see
      # https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/llvm/tools/llvm-shlib/CMakeLists.txt#L82-L85
      # osx currently fails as well, see https://github.com/llvm/llvm-project/issues/64657
      skip: true  # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - ninja
        - libcxx-devel {{ version }}  # [osx]
      host:
        - libcxx-devel {{ version }}  # [osx]
        - {{ pin_subpackage("libllvm" ~ major_ver, exact=True) }}
        - zlib {{ zlib }}
        - zstd {{ zstd }}
      run_constrained:
        - llvmdev {{ version }}
    test:
      commands:
        - test -f $PREFIX/lib/libLLVM-C.{{ major_ver }}.dylib   # [osx]
        - if not exist %LIBRARY_BIN%\LLVM-C.dll exit 1          # [win]
        - if not exist %LIBRARY_LIB%\LLVM-C.lib exit 1          # [win]

  - name: lit
    build:
      script: python -m pip install llvm/utils/lit --no-deps --no-build-isolation -vv
      entry_points:
        # upstream LLVM is inconsistent; there's one way specified in lit's setup.py...
        - lit = lit.main:main
        # ... and then the CMake files we install here (e.g. AddLLVM.cmake) look for another
        - llvm-lit = lit.main:main
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
    test:
      imports:
        - lit
      commands:
        - lit -h
        - llvm-lit -h

about:
  home: https://llvm.org/
  dev_url: https://github.com/llvm/llvm-project
  doc_url: https://llvm.org/docs/
  license: Apache-2.0 WITH LLVM-exception
  license_file: llvm/LICENSE.TXT
  license_family: Apache
  summary: Development headers and libraries for LLVM
  description: |
    A toolkit for the construction of highly optimized compilers,
    optimizers, and run-time environments.

extra:
  skip-lints:
    # there are false positives for these checks,
    # for some of the individual outputs.
    - missing_tests
    - wrong_output_script_key
  recipe-maintainers:
    - JohanMabille
    - inducer
    - jakirkham
    - mingwandroid
    - SylvainCorlay
    - isuruf
    - timsnyder
    - xhochy
    - h-vetinari
    - danpetry
  feedstock-name: llvmdev
