# (Mostly) blatant copy of https://github.com/numba/llvmlite/tree/master/conda-recipes/llvmdev

{% set shortversion = "3.9" %}
{% set version = "3.9.1" %}
{% set sha256 = "1fd90354b9cf19232e8f168faf2220e79be555df3aa743242700879e8fd329ee" %}

package:
  name: llvmdev
  version: {{ version }}

source:
  fn: llvm-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    # https://llvm.org/bugs/show_bug.cgi?id=15356
    - llvm-elf-relocation.patch
    # https://llvm.org/bugs/show_bug.cgi?id=25565
    - llvm-build-race-condition.patch
    # http://lists.llvm.org/pipermail/llvm-dev/2016-January/094520.html
    - llvm-lto-static.patch  # [win]

build:
  number: 0
  skip: true  # [(unix and py3k) or (win and py<35)]
  features:   # [win and py35]
    - vc14    # [win and py35]

requirements:
  build:
    - toolchain
    - cmake
    # Needed to unpack the source tarball
    - m2-xz  # [py27 and win32]
    - m2w64-xz  # [py27 and win64]
    # Needed to build LLVM
    - python
    - system  # [linux and not armv7l]
  run:
    - system  # [linux and not armv7l]

test:
  requires:                                                  # [win]
    - python {{ environ['PY_VER'] + '*' }}                   # [win]

  commands:
    - $PREFIX/bin/llvm-config --libs                         # [not win]
    - $PREFIX/bin/llc -version                               # [not win]

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1     # [win]

    - test -f $PREFIX/include/llvm/Pass.h                    # [unix]
    - test -f $PREFIX/lib/libLLVMCore.a                      # [not win]

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM

extra:
  recipe-maintainers:
    - inducer
    - pitrou
    - jakirkham
    - mingwandroid
    - mattwala
    - SylvainCorlay
