
{% if ppc64le %}

{% set version = "6.0.1" %}
{% set sha256 = "b6d6c324f9c71494c0ccaf3dac1f16236d970002b42bb24a6c9e1634f7d0f4e2" %}
{% set build_number = "0" %}

{% else %}

{% set version = "6.0.1" %}
{% set sha256 = "b6d6c324f9c71494c0ccaf3dac1f16236d970002b42bb24a6c9e1634f7d0f4e2" %}

{% set build_number = "3" %}

{% endif %}

package:
  name: llvmdev
  version: {{ version }}

source:
  fn: llvm-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    - CodeView_registers.patch
    - llvm-lto-static.patch   # [win]
    - twine_cfg_undefined_behavior.patch
    - intel-svml.patch
{% if llvm_variant == "cling" %}
    - cling-patches/0001-Add-interface-to-create-DyLib-from-dlopen-handle.patch
    - cling-patches/0002-Add-cling-as-tool-to-be-built.patch
    - cling-patches/0003-Do-NOT-remove-original-functions-after-inlining-them.patch
    - cling-patches/0004-From-Lang-Hames-first-step-towards-RuntimeDyld-resol.patch
    - cling-patches/0005-Update-DEBUG-to-current-llvm-API.patch
    - cling-patches/0006-Mark-weak-symbols-weak-apparently-NFC.patch
    - 0001-Transforms-Add-missing-header-for-InstructionCombini.patch
    - cling-patches/0008-Adapt-to-llvm-r272382.patch
    - twine_cfg_undefined_behavior.patch
{% endif %}

build:
  number: {{ build_number }}
  # string: {{ llvm_variant }}_{{ build_number }}
  skip:  true  # [win and vc<14]
  ignore_run_exports:
    - zlib
  missing_dso_whitelist:  # [osx]
    - '*'  # [osx]
  features:
    - cling    # [llvm_variant == 'cling']

requirements:
  build:
    # We cannot do this on macOS
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - vs2017_win-64  # [win64]
    - vs2017_win-32  # [win32]
    - cmake
    - ninja     # [win]
    - python 3.7.*
    - zlib
  run:
    - vs2015_runtime  # [win]

test:
  requires:
    - cling-patches    # [llvm_variant == 'cling']
  files:
    - numba-3016.ll

  commands:
    - $PREFIX/bin/llvm-config --libs                         # [not win]
    - $PREFIX/bin/llc -version                               # [not win]

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1        # [win]

    - test -f $PREFIX/include/llvm/Pass.h                    # [unix]
    - test -f $PREFIX/lib/libLLVMCore.a                      # [not win]


    - opt -S -vector-library=SVML -mcpu=haswell -O3 numba-3016.ll -o out.ll
    - findstr __svml_sin4 out.ll                             # [win]
    - grep __svml_sin4 out.ll                                # [unix]

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM

extra:
  recipe-maintainers:
    - inducer
    - pitrou
    - jakirkham
    - mingwandroid
    - mattwala
    - SylvainCorlay
    - isuruf
