{% set version = "17.0.6" %}
{% set major_ver = version.split(".")[0] %}

# as of LLVM 17, we expect an "rc" suffix for the release candidates
{% set extra = "rc" if version.split(".")[-1] not in "0123456789" else "" %}
{% set extra = "git" if version.split(".")[-1] == "dev0" else extra %}

package:
  name: llvm-package
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
  sha256: 58a8818c60e6627064f312dbf46c02d9949956558340938b71cf731ad8bc0813
  patches:
    - patches/0001-pass-through-QEMU_LD_PREFIX-SDKROOT.patch
    # - patches/0002-restore-macos-10.9-support.patch
    # # this patch adds the needed version numbers to 
    # - patches/0003-change-osx-version-for-libllvm-c.patch
    # These two patches remove expected test failures.
    - patches/0004-remove-unsupported-intrinsic-test.patch
    - patches/0005-remove-permission-based-unit-tests.patch
    # # A different approach to this fix: https://github.com/conda-forge/llvmdev-feedstock/commit/1da42e54b055d26bc58da77bd1f88ad460ac90f4
    # # - patches/MSVC_DIA_SDK_path_fix.diff  # [win]

build:
  number: 2
  merge_build_host: false

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - python
    - libcxx {{ major_ver }}    # [osx]
    - patch                     # [not win]
    - m2-patch                  # [win]
    - git                       # [not win]
  host:
    - libcxx {{ major_ver }}    # [osx]
    - backtrace                 # [unix]
    - libffi {{ libffi }}
    - libxml2 {{ libxml2 }}
    - zlib {{ zlib }}
    - zstd {{ zstd }}

outputs:
  # Contains everything
  - name: llvmdev
    script: install_llvm.sh   # [unix]
    script: install_llvm.bat  # [win]
    build:
      activate_in_script: true
      # skip: true  # [(win and vc<14)]
      # missing_dso_whitelist:  # [s390x]
      #   - $RPATH/ld64.so.1    # [s390x]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - python
        - m2-sed                  # [win]
        - libcxx {{ major_ver }}  # [osx]
      host:
        - libcxx {{ major_ver }}  # [osx]
        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
        - {{ pin_subpackage("libllvm-c" + major_ver, exact=True) }}     # [win]
        - {{ pin_subpackage("llvm-tools", exact=True) }}
        - libffi {{ libffi }}
        - libxml2 {{ libxml2 }}
        - zlib {{ zlib }}
        - zstd {{ zstd }}
      run:
        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
        - {{ pin_subpackage("libllvm-c" + major_ver, exact=True) }}     # [win]
        - {{ pin_subpackage("llvm-tools", exact=True) }}
        - libcxx >={{ major_ver }}                           # [osx]
      run_constrained:
        - llvm        {{ version }}
        - llvm-tools  {{ version }}
        - clang       {{ version }}
        - clang-tools {{ version }}
    test:
      requires:
        - ripgrep  # [win]
      commands:
        - $PREFIX/bin/llvm-config --libs                                # [not win]
        - test -f $PREFIX/include/llvm/Pass.h                           # [not win]
        - test -f $PREFIX/lib/libLLVMCore.a                             # [not win]
        - $PREFIX/libexec/llvm/not false                                # [not win]
        - $PREFIX/bin/llvm-nm --help                                    # [not win]
        - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1               # [win]
        - if not exist "%LIBRARY_PREFIX%"\\libexec\llvm\not.exe exit 1  # [win]
        - if not exist "%LIBRARY_BIN%"\\llvm-nm.exe exit 1              # [win]
        - cd "%LIBRARY_BIN%" && llvm-nm.exe --help                     # [win]
        # ensure we've correctly inserted %VSINSTALLDIR% into the CMake metadata for LLVM;
        # we're looking for: `INTERFACE_LINK_LIBRARIES "$ENV{VSINSTALLDIR}/DIA SDK/lib/amd64/diaguids.lib;[...]`instead
        - rg -e "INTERFACE_LINK_LIBRARIES\s\"\$ENV\{VSINSTALLDIR\}[/\w\s]+/diaguids\.lib" %LIBRARY_LIB%\cmake\llvm\LLVMExports.cmake  # [win]

  # Contains the shared libraries. To make different LLVM libraries co-installable
  # soversion is appended to the package name.
  - name: libllvm{{ major_ver }}
    script: install_llvm.sh  # [not win]
    build:
      activate_in_script: true
      # skip: true  # [win and vc<14]
      run_exports:                                                    # [not win]
        - {{ pin_subpackage("libllvm" + major_ver, max_pin="x.x") }}  # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - ninja                    # [not win]
        - cmake                    # [not win]
        - python                   # [not win]
        - libcxx {{ major_ver }}  # [osx]
      host:
        - libcxx {{ major_ver }}  # [osx]
        - libffi {{ libffi }}
        - libxml2 {{ libxml2 }} # [unix]
        - zlib {{ zlib }}
        - zstd {{ zstd }}
      run:
        # we need to do this manually because clang_bootstrap has no run-export
        - libcxx >={{ major_ver }}  # [osx]
        # - {{ pin_compatible('libffi', max_pin='x.x') }}  # [unix]
        # - zlib {{ zlib }}    # [osx]
    test:
      commands:
        - test -f $PREFIX/lib/libLLVM-{{ major_ver }}{{ extra }}.so     # [linux]
        - test -f $PREFIX/lib/libLLVM-{{ major_ver }}{{ extra }}.dylib  # [osx]
        # Make sure libffi was linked
        - otool -L $PREFIX/lib/libLLVM-{{ major_ver }}{{ extra }}.dylib | grep -i ffi  # [osx]
        - ldd $PREFIX/lib/libLLVM-{{ major_ver }}{{ extra }}.so | grep -i ffi          # [linux]

  # This is a meta package so that people can use the latest libllvm and also
  # for run_exports
  - name: llvm
    build:
      # skip: true  # [(win and vc<14)]
      run_exports:                                                    # [not win]
        - {{ pin_subpackage("libllvm" + major_ver, max_pin="x.x") }}  # [not win]
    requirements:
      build:
      host:
        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}     # [not win]
        - libxml2 {{ libxml2 }}
        - libffi {{ libffi }}
        - zlib {{ zlib }}
        - zstd {{ zstd }}
      run:                                                            # [not win]
        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}     # [not win]
      run_constrained:
        - llvmdev     {{ version }}
        - llvm-tools  {{ version }}
        - clang       {{ version }}
        - clang-tools {{ version }}
    test:
      commands:
        - echo "Hello World!"

  # Contains LLVM tools
  - name: llvm-tools
    script: install_llvm.sh   # [unix]
    script: install_llvm.bat  # [win]
    build:
      activate_in_script: true
      # skip: true  # [(win and vc<14)]
      # missing_dso_whitelist:  # [s390x]
      #   - $RPATH/ld64.so.1    # [s390x]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - python
        - libcxx {{ major_ver }}  # [osx]
      host:
        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
        - libffi {{ libffi }}
        - libxml2 {{ libxml2 }}
        - zlib {{ zlib }}
        - zstd {{ zstd }}
        - libcxx {{ major_ver }}  # [osx]
      run:
        - {{ pin_subpackage("libllvm" + major_ver, exact=True) }}
        - libcxx >={{ major_ver }}  # [osx]
      run_constrained:
        - llvm        {{ version }}
        - llvmdev     {{ version }}
        # - clang       {{ version }}
        # - clang-tools {{ version }}
    test:
      commands:
        - $PREFIX/bin/llc -version                               # [not win]
        # The test for windows is split into two lines instead of having it in one line
        # like its unix variant because of a YAML parsing issue.
        - if not exist "%LIBRARY_BIN%"\\llc.exe exit 1           # [win]
        - cd "%LIBRARY_BIN%" && llc -version                     # [win]
        - test ! -f $PREFIX/bin/llvm-config                      # [not win]
        - if not exist "%LIBRARY_BIN%"\\llvm-config.exe exit 1       # [win]

  ########
  # TODO - enable and include libllvm-c
  ########

  - name: lit
    build:
      script: python -m pip install llvm/utils/lit --no-deps --no-build-isolation -vv
      entry_points:
        # upstream LLVM is inconsistent; there's one way specified in lit's setup.py...
        - lit = lit.main:main
        # ... and then the CMake files we install here (e.g. AddLLVM.cmake) look for another
        - llvm-lit = lit.main:main
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
    test:
      imports:
        - lit
      commands:
        - lit -h
        - llvm-lit -h

about:
  home: https://llvm.org/
  dev_url: https://github.com/llvm/llvm-project
  doc_url: https://llvm.org/docs/
  license: Apache-2.0 WITH LLVM-exception
  license_file: llvm/LICENSE.TXT
  license_family: Apache
  summary: Development headers and libraries for LLVM
  description: |
    A toolkit for the construction of highly optimized compilers,
    optimizers, and run-time environments.

extra:
  skip-lints:
    # there are false positives for these checks,
    # for some of the individual outputs.
    - missing_tests
    - wrong_output_script_key
  recipe-maintainers:
    - JohanMabille
    - inducer
    - jakirkham
    - mingwandroid
    - SylvainCorlay
    - isuruf
    - timsnyder
    - xhochy
    - h-vetinari
    - danpetry
  feedstock-name: llvmdev