{% set version = "7.0.1" %}
{% set sha256 = "a38dfc4db47102ec79dcc2aa61e93722c5f6f06f0a961073bd84b78fb949419b" %}

{% set build_number = "1" %}

package:
  name: llvmdev
  version: {{ version }}

source:
  fn: llvm-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    # http://lists.llvm.org/pipermail/llvm-dev/2016-January/094520.html
    - llvm-lto-static.patch   # [win]
    # Intel SVML optimizations
    - intel-svml.patch
    # https://reviews.llvm.org/D44140 Fix LLVM-C symbol export
    - 0001-Transforms-Add-missing-header-for-InstructionCombini.patch
    # undefined behavior bug due to Twine usage
    - twine_cfg_undefined_behavior.patch
    - partial-testing.patch
    - D47188-svml-VF.patch    # Fixes vectorizer and extends SVML support

build:
  number: {{ build_number }}
  string: {{ llvm_variant }}_{{ build_number }}
  ignore_run_exports:
    - zlib
  missing_dso_whitelist:  # [osx]
    - '*'  # [osx]
  skip:  true  # [win and vc<14]

requirements:
  build:
    - toolchain
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja     # [win]
    - python
    - libcxx    4.0.1  # [osx]
  run:
    - vc 14  # [win]
    - llvm-meta {{ version }}|{{ version }}.*

test:
  files:
    - numba-3016.ll

  commands:
    - $PREFIX/bin/llvm-config --libs                         # [not win]
    - $PREFIX/bin/llc -version                               # [not win]

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1        # [win]

    - test -f $PREFIX/include/llvm/Pass.h                    # [unix]
    - test -f $PREFIX/lib/libLLVMCore.a                      # [not win]

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM

extra:
  recipe-maintainers:
    - inducer
    - pitrou
    - jakirkham
    - mingwandroid
    - mattwala
    - SylvainCorlay
    - isuruf
